---
- name: Create a new database with name 'neutron'
  community.mysql.mysql_db:
    name: neutron
    state: present
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"

- name: Grant access to the database neutron.* to 'neutron'@'localhost'
  community.mysql.mysql_query:
    query: "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ NEUTRON_DB_PASSWORD }}';"
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"

- name: Grant access to the database neutron.* to 'neutron'@'%'
  community.mysql.mysql_query:
    query: "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ NEUTRON_DB_PASSWORD }}';"
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"

- name: Flush privileges for neutron
  community.mysql.mysql_query:
    query: "FLUSH PRIVILEGES;"
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ MARIADB_ROOT_PASSWORD }}"

- name: Create a user neutron
  openstack.cloud.identity_user:
    state: present
    name: neutron
    password: "{{ NEUTRON_USER_PASSWORD }}"
    domain: default

- name: Grant an admin role on the user neutron in the project service
  openstack.cloud.role_assignment:
    user: neutron
    role: admin
    project: service

- name: Create a service for neutron
  openstack.cloud.catalog_service:
     state: present
     name: neutron
     type: network
     description: Openstack Networking

- name: Create the neutron service public
  openstack.cloud.endpoint:
     service: neutron
     endpoint_interface: public
     url: http://localhost:9696
     region: RegionOne
     state: present

- name: Create the neutron service internal
  openstack.cloud.endpoint:
     service: neutron
     endpoint_interface: internal
     url: http://neutron:9696
     region: RegionOne
     state: present

- name: Create the neutron service admin
  openstack.cloud.endpoint:
     service: neutron
     endpoint_interface: admin
     url: http://localhost:9696
     region: RegionOne
     state: present

- name: Build a neutron image
  community.docker.docker_image_build:
    name: neutron:24.0.0
    path: "{{playbook_dir}}/dockers/neutron"
    dockerfile: Dockerfile

- name: Create metadata_agent.ini file
  ansible.builtin.template:
    src: "{{ role_path }}/files/metadata_agent.ini"
    dest: ~/metadata_agent.ini
    mode: '0444'

- name: Create neutron.conf file
  ansible.builtin.template:
    src: "{{ role_path }}/files/neutron.conf"
    dest: ~/neutron.conf
    mode: '0444'

- name: Create ml2_conf.ini file
  ansible.builtin.template:
    src: "{{ role_path }}/files/ml2_conf.ini"
    dest: ~/ml2_conf.ini
    mode: '0444'

- name: "Run a neutron-server"
  community.docker.docker_container:
    name: neutron
    image: neutron:24.0.0
    state: started
    restart_policy: always
    networks:
      - name: openstack
    ports:
      - "9696:9696"
    volumes:
      - ~/metadata_agent.ini:/etc/neutron/metadata_agent.ini
      - ~/neutron.conf:/etc/neutron/neutron.conf
      - ~/ml2_conf.ini:/etc/neutron/plugins/ml2/ml2_conf.ini
    command: neutron-server

- name: Run a neutron container with command neutron-db-manage .. upgrade head
  community.docker.docker_container:
    name: neutron-db-manage-upgrade-head
    image: neutron:24.0.0
    state: started
    networks:
      - name: openstack
    volumes:
      - ~/metadata_agent.ini:/etc/neutron/metadata_agent.ini
      - ~/neutron.conf:/etc/neutron/neutron.conf
      - ~/ml2_conf.ini:/etc/neutron/plugins/ml2/ml2_conf.ini
    command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  retries: 3
  delay: 3 

- name: "Run a {{ item }}"
  community.docker.docker_container:
    name: "{{ item }}"
    image: neutron:24.0.0
    state: started
    restart_policy: always
    networks:
      - name: openstack
    volumes:
      - ~/metadata_agent.ini:/etc/neutron/metadata_agent.ini
      - ~/neutron.conf:/etc/neutron/neutron.conf
      - ~/ml2_conf.ini:/etc/neutron/plugins/ml2/ml2_conf.ini
    command: "{{ item }}"
  with_items:
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent